### ISSUE TITLE
Errors after installing

### ISSUE THREAD

**Issue by nitaybz** [aaronkampmeier/homebridge-opensprinkler-system#1]
Hey!
Trying to install your plugin.
i get this error:
```
May 18 15:46:36 raspberrypi homebridge[6127]: [5/18/2020, 3:46:36 PM] [OpenSprinkler] TypeError: Cannot read property 'snames' of undefined
May 18 15:46:36 raspberrypi homebridge[6127]: at new System (/usr/lib/node_modules/homebridge-opensprinkler-system/lib/system.js:16:35)
May 18 15:46:36 raspberrypi homebridge[6127]: at openSprinklerApi.getStatus.then (/usr/lib/node_modules/homebridge-opensprinkler-system/lib/system.js:74:51)
May 18 15:46:36 raspberrypi homebridge[6127]: at processTicksAndRejections (internal/process/task_queues.js:86:5)
May 18 15:46:37 raspberrypi homebridge[6127]: (node:6127) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'snames' of undefined
May 18 15:46:37 raspberrypi homebridge[6127]: at new System (/usr/lib/node_modules/homebridge-opensprinkler-system/lib/system.js:16:35)
May 18 15:46:37 raspberrypi homebridge[6127]: at openSprinklerApi.getStatus.then (/usr/lib/node_modules/homebridge-opensprinkler-system/lib/system.js:74:51)
May 18 15:46:37 raspberrypi homebridge[6127]: at processTicksAndRejections (internal/process/task_queues.js:86:5)
May 18 15:46:37 raspberrypi homebridge[6127]: (node:6127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
May 18 15:46:37 raspberrypi homebridge[6127]: (node:6127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is my config (password hidden):
```
     {
            "platform": "OpenSprinkler",
            "host": "10.0.0.**:8080",
            "password": {"md5": "*****"},
            "defaultDurationSecs": 1800,
            "pollIntervalMs": 5000
        },

```

Please assist :)

**Comment by nitaybz** [comment]
I found out that the error was caused by the md5 version of the password... changed to plain and it works... maybe catch that error and show password wrong error?
anyway, I'm closing it...
